#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

PLUGIN_DIR="plugins"
PLUGIN_CONFIG="plugins.conf.yaml"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
echo '[1/7] git submodule update'
git submodule update --init --recursive --remote --quiet
echo '[2/7] git submodule sync'
git submodule sync --recursive --quiet
echo '[3/7] git submodule stash'
git submodule foreach --recursive --quiet 'git stash' --quiet
echo '[4/7] git submodule fetch'
git submodule foreach --recursive --quiet 'git fetch --tags' --quiet
echo '[5/7] git submodule pull'
git submodule foreach --recursive --quiet 'git pull origin HEAD' --quiet
echo '[6/7] create links to dotbot plugins'
"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${PLUGIN_DIR}/${PLUGIN_CONFIG}" "${@}"							# Init dotbot plugins
echo '[7/7] install configuration'
"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" --plugin-dir "${BASEDIR}/${PLUGIN_DIR}/" -c "${CONFIG}" "${@}"     # Configuration
