#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

PLUGIN_DIR="plugins"
PLUGIN_CONFIG="plugins.conf.yaml"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule sync --recursive
git submodule foreach --recursive 'git stash'
git submodule foreach --recursive 'git fetch --tags'
git submodule foreach --recursive 'git pull origin HEAD'

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${PLUGIN_DIR}/${PLUGIN_CONFIG}" "${@}"							# Init dotbot plugins
"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" --plugin-dir "${BASEDIR}/${PLUGIN_DIR}/" -c "${CONFIG}" "${@}"     # Configuration
